version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    restart: always
    build:
      context: web
      dockerfile: Dockerfile
    image: django-k8s:1.0.0
    env_file:
      - web/.env
    environment:
      - PORT=8020
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh"
    volumes: 
      - staticfiles:/app/staticfiles/
  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - web/.env
    expose:
      - 5433
    ports: 
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose:
      - 6380
    ports: 
      - "6380:6380"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380


volumes:
  staticfiles:
     external: true       
  postgres_data: 
  redis_data: 