apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment 
    spec:
      containers:
      - name: iac-python
        image: codingforentrepreneurs/iac-python:latest
        env:
         - name: PORT
           value: "8181"
        resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
        ports:
        - containerPort: 8181
