apiVersion: v1
kind: Service
metadata:
  name: django-k8-service
spec:
  type: LoadBalancer
  selector:
    app: django-k8s-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
